name: git-tui
version: 1.3.0
summary: A collection of human friendly terminal interfaces for git.
description: A collection of human friendly terminal interfaces for git.

grade: stable
confinement: strict
base: core20

apps:
  git-tui:
    command: usr/bin/git-tui
    plugs:
      - home

parts:
  git-tui:
    plugin: cmake
    source: https://github.com/ArthurSonzogni/git-tui
    source-type: git
    source-depth: 1
    build-packages:
      - build-essential
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
    stage-packages:
      - git

passthrough:
  title: git-tui
  license: MIT
